### PR TITLE
Modify metrictemplete to metrictemplate

### PR DESCRIPTION
**Pull request by wayilau**
Simply modify the file name.

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is the change?

**Comment by JaredTan95** [comment]
> What is the change?

Seems renamed filename.

**Comment by wu-sheng** [comment]
But I can't tell the difference of file name. GitHub shows name change, but the origin and current are the same.

**Comment by wayilau** [comment]
origin name: metrictemplete

**Comment by wu-sheng** [comment]
Oh, I see. Typo :)

**Pull request merged**
